apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: LoadBalancer # Use NodePort or ClusterIP for internal services, LoadBalancer for external
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: flask-app # This should match the labels of the pods you want to expose
